#!/bin/env python
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This demo only needs the CFU firmware path, not the TensorFlow Lite Micro
# model tree, so keep builds small and focused.
SKIP_TFLM := 1

# This variable lists symbols to define to the C preprocessor.
export DEFINES :=
DEFINES += NDEBUG
DEFINES += NPROFILE

# run-renode feeds these menu choices:
#   3: Project menu
#   0: Run PRO CFU demo
#   x: Return to main menu, then expect kills Renode
RUN_MENU_ITEMS := 3 0 x
TEST_MENU_ITEMS := 3 0 x


include ../proj.mk
